spring:
  main:
    banner-mode: off

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc.batch_size: 20
        default_batch_fetch_size: 20

  datasource:
    url: jdbc:h2:mem:voting
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  mvc:
    format:
      date: iso
      date-time: iso

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    ru.graduation.voting: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.orm.jpa.JpaTransactionManager: debug
  charset:
    console: UTF-8
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(%5p) %-65.65(%clr(%logger{50}){cyan}) : %msg%n"